services:
  front:
    image: front-app
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: front-app
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules